### ISSUE TITLE
Where can i get deploy.sh?

### ISSUE THREAD

**Issue by GhostRule** [purplepalmdash/blogsource#1]
您好，我最近正在尝试离线安装kubeflow，遇到一些问题。我想问一下您在离线安装kubeflow时，博文中所提及的deploy.sh，是官方提供的，还是您个人编写的？希望您能给予解答，谢谢。

**Comment by purplepalmdash** [comment]
自己编写的，主要用来load离线需要的镜像文件。

**Comment by GhostRule** [comment]
感谢您的回答，请问您还记得当时是怎么获取离线需要的镜像文件的列表的吗？

**Comment by purplepalmdash** [comment]
用的比较笨的方法，先在单节点上在线布一次记录下所需要的镜像，然后传到内网

**Comment by GhostRule** [comment]
谢谢您的回答，我是后来在一个文件中找到了各个需求的镜像名称，然后手动下载解决了
